# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Spree::Country.create!(iso_name:"JAPAN", name:"日本", iso3:"JPN", iso:"JP", numcode:"392", states_required: true)
country = Spree::Country.find_by_name('日本')
Spree::State.create!(name:"北海道", abbr:"hokkaido", country:country)
Spree::State.create!(name:"青森県", abbr:"aomori", country:country)
Spree::State.create!(name:"岩手県", abbr:"iwate", country:country)
Spree::State.create!(name:"宮城県", abbr:"miyagi", country:country)
Spree::State.create!(name:"秋田県", abbr:"akita", country:country)
Spree::State.create!(name:"山形県", abbr:"yamagata", country:country)
Spree::State.create!(name:"福島県", abbr:"fukushima", country:country)
Spree::State.create!(name:"茨城県", abbr:"ibaraki", country:country)
Spree::State.create!(name:"栃木県", abbr:"tochigi", country:country)
Spree::State.create!(name:"群馬県", abbr:"gunma", country:country)
Spree::State.create!(name:"埼玉県", abbr:"saitama", country:country)
Spree::State.create!(name:"千葉県", abbr:"chiba", country:country)
Spree::State.create!(name:"東京都", abbr:"tokyo", country:country)
Spree::State.create!(name:"神奈川県", abbr:"kanagawa", country:country)
Spree::State.create!(name:"新潟県", abbr:"niigata", country:country)
Spree::State.create!(name:"富山県", abbr:"toyama", country:country)
Spree::State.create!(name:"石川県", abbr:"ishikawa", country:country)
Spree::State.create!(name:"福井県", abbr:"fukui", country:country)
Spree::State.create!(name:"山梨県", abbr:"yamanashi", country:country)
Spree::State.create!(name:"長野県", abbr:"nagano", country:country)
Spree::State.create!(name:"岐阜県", abbr:"gifu", country:country)
Spree::State.create!(name:"静岡県", abbr:"shizuoka", country:country)
Spree::State.create!(name:"愛知県", abbr:"aichi", country:country)
Spree::State.create!(name:"三重県", abbr:"mie", country:country)
Spree::State.create!(name:"滋賀県", abbr:"shiga", country:country)
Spree::State.create!(name:"京都府", abbr:"kyoto", country:country)
Spree::State.create!(name:"大阪府", abbr:"osaka", country:country)
Spree::State.create!(name:"兵庫県", abbr:"hyogo", country:country)
Spree::State.create!(name:"奈良県", abbr:"nara", country:country)
Spree::State.create!(name:"和歌山県", abbr:"wakayama", country:country)
Spree::State.create!(name:"鳥取県", abbr:"tottori", country:country)
Spree::State.create!(name:"島根県", abbr:"shimane", country:country)
Spree::State.create!(name:"岡山県", abbr:"okayama", country:country)
Spree::State.create!(name:"広島県", abbr:"hiroshima", country:country)
Spree::State.create!(name:"山口県", abbr:"yamaguchi", country:country)
Spree::State.create!(name:"徳島県", abbr:"tokushima", country:country)
Spree::State.create!(name:"香川県", abbr:"kagawa", country:country)
Spree::State.create!(name:"愛媛県", abbr:"ehime", country:country)
Spree::State.create!(name:"高知県", abbr:"kochi", country:country)
Spree::State.create!(name:"福岡県", abbr:"fukuoka", country:country)
Spree::State.create!(name:"佐賀県", abbr:"saga", country:country)
Spree::State.create!(name:"長崎県", abbr:"nagasaki", country:country)
Spree::State.create!(name:"熊本県", abbr:"kumamoto", country:country)
Spree::State.create!(name:"大分県", abbr:"oita", country:country)
Spree::State.create!(name:"宮崎県", abbr:"miyazaki", country:country)
Spree::State.create!(name:"鹿児島県", abbr:"kagoshima", country:country)
Spree::State.create!(name:"沖縄県", abbr:"okinawa", country:country)

#Spree::Core::Engine.load_seed if defined?(Spree::Core)
#Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
