# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Spree::Country.create!(iso_name:"JAPAN", name:"日本", iso3:"JPN", iso:"JP", numcode:"392", states_required: true)
country = Spree::Country.find_by_name('日本')
Spree::State.create!(name:"北海道", abbr:"北海道", country:country)
Spree::State.create!(name:"青森県", abbr:"青森県", country:country)
Spree::State.create!(name:"岩手県", abbr:"岩手県", country:country)
Spree::State.create!(name:"宮城県", abbr:"宮城県", country:country)
Spree::State.create!(name:"秋田県", abbr:"秋田県", country:country)
Spree::State.create!(name:"山形県", abbr:"山形県", country:country)
Spree::State.create!(name:"福島県", abbr:"福島県", country:country)
Spree::State.create!(name:"茨城県", abbr:"茨城県", country:country)
Spree::State.create!(name:"栃木県", abbr:"栃木県", country:country)
Spree::State.create!(name:"群馬県", abbr:"群馬県", country:country)
Spree::State.create!(name:"埼玉県", abbr:"埼玉県", country:country)
Spree::State.create!(name:"千葉県", abbr:"千葉県", country:country)
Spree::State.create!(name:"東京都", abbr:"東京都", country:country)
Spree::State.create!(name:"神奈川県", abbr:"神奈川県", country:country)
Spree::State.create!(name:"新潟県", abbr:"新潟県", country:country)
Spree::State.create!(name:"富山県", abbr:"富山県", country:country)
Spree::State.create!(name:"石川県", abbr:"石川県", country:country)
Spree::State.create!(name:"福井県", abbr:"福井県", country:country)
Spree::State.create!(name:"山梨県", abbr:"山梨県", country:country)
Spree::State.create!(name:"長野県", abbr:"長野県", country:country)
Spree::State.create!(name:"岐阜県", abbr:"岐阜県", country:country)
Spree::State.create!(name:"静岡県", abbr:"静岡県", country:country)
Spree::State.create!(name:"愛知県", abbr:"愛知県", country:country)
Spree::State.create!(name:"三重県", abbr:"三重県", country:country)
Spree::State.create!(name:"滋賀県", abbr:"滋賀県", country:country)
Spree::State.create!(name:"京都府", abbr:"京都府", country:country)
Spree::State.create!(name:"大阪府", abbr:"大阪府", country:country)
Spree::State.create!(name:"兵庫県", abbr:"兵庫県", country:country)
Spree::State.create!(name:"奈良県", abbr:"奈良県", country:country)
Spree::State.create!(name:"和歌山県", abbr:"和歌山県", country:country)
Spree::State.create!(name:"鳥取県", abbr:"鳥取県", country:country)
Spree::State.create!(name:"島根県", abbr:"島根県", country:country)
Spree::State.create!(name:"岡山県", abbr:"岡山県", country:country)
Spree::State.create!(name:"広島県", abbr:"広島県", country:country)
Spree::State.create!(name:"山口県", abbr:"山口県", country:country)
Spree::State.create!(name:"徳島県", abbr:"徳島県", country:country)
Spree::State.create!(name:"香川県", abbr:"香川県", country:country)
Spree::State.create!(name:"愛媛県", abbr:"愛媛県", country:country)
Spree::State.create!(name:"高知県", abbr:"高知県", country:country)
Spree::State.create!(name:"福岡県", abbr:"福岡県", country:country)
Spree::State.create!(name:"佐賀県", abbr:"佐賀県", country:country)
Spree::State.create!(name:"長崎県", abbr:"長崎県", country:country)
Spree::State.create!(name:"熊本県", abbr:"熊本県", country:country)
Spree::State.create!(name:"大分県", abbr:"大分県", country:country)
Spree::State.create!(name:"宮崎県", abbr:"宮崎県", country:country)
Spree::State.create!(name:"鹿児島県", abbr:"鹿児島県", country:country)
Spree::State.create!(name:"沖縄県", abbr:"沖縄県", country:country)

#Spree::Core::Engine.load_seed if defined?(Spree::Core)
#Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
